[package]
name = "snowland-workflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.14.1"
zip = "0.5.13"
thiserror = "1.0.30"

[features]
build-win = []
build-linux = []
