[workspace]
members = [
    "control-panel/implementation",
    "control-panel/macro",

    "hosts/linux",
    "hosts/win",

    "libraries/misc",
    "libraries/core",
    "libraries/ipc",
    "libraries/x11-wrapper"
]

[profile.release]
lto = true
codegen-units = 1
