[package]
name = "snowland-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
snowland-ipc = { path = "../../libraries/ipc", features = ["poll"] }
log = "0.4.16"
pretty_env_logger = "0.4.0"

[build-dependencies]
cbindgen = "0.21.0"
