name: Build

on:
  push: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [windows, linux]
        include:
          - platform: windows
            runner: windows-latest
          - platform: linux
            runner: ubuntu-latest

    runs-on: ${{ matrix.runner }}
    env:
      SNOWLAND_PACKAGE_NAME: snowland-${{ matrix.platform }}.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout flutter
        uses: actions/checkout@v2
        with:
          repository: flutter/flutter
          path: ${{ github.workspace }}/flutter
          ref: 3f775d864e0ee999d880d199563055188add96cd

      - name: Add flutter to path
        run: |
          echo "${GITHUB_WORKSPACE}/flutter/bin" >> $GITHUB_PATH

      - name: Enable flutter desktop
        run: flutter config --enable-${{ matrix.platform }}-desktop

      - name: Cache Rust
        uses: Swatinem/rust-cache@v1

      - name: Package software
        run: cargo run snowland-workflow

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }} package
          path: target/release/snowland-${{ matrix.platform }}.zip
