name: Build

on:
  push: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows, linux]
        include:
          - platform: windows
            runner: windows-latest
          - platform: linux
            runner: ubuntu-latest

    runs-on: ${{ matrix.runner }}
    env:
      SNOWLAND_PACKAGE_NAME: snowland-${{ matrix.platform }}.zip

    steps:
      - name: Update system repositories
        if: runner.os == 'Linux'
        run: sudo apt update

      - name: Upgrade system
        if: runner.os == 'Linux'
        run: sudo apt full-upgrade

      - name: Install required dependencies
        if: runner.os == 'Linux'
        run: sudo apt install libgl1-mesa-dev libxrandr-dev libgtk-3-dev

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout flutter
        uses: actions/checkout@v2
        with:
          repository: flutter/flutter
          path: ${{ github.workspace }}/flutter

      - name: Add flutter to path
        shell: bash
        run: |
          echo "${GITHUB_WORKSPACE}/flutter/bin" >> $GITHUB_PATH

      - name: Switch flutter channel and checkout commit
        run: |
          flutter channel master
          cd ${{ github.workspace }}/flutter
          git checkout 3f775d864e0ee999d880d199563055188add96cd

      - name: Enable flutter desktop
        run: flutter config --enable-${{ matrix.platform }}-desktop

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Cache Rust
        uses: Swatinem/rust-cache@v1

      - name: Package software
        run: cargo run --bin snowland-workflow --package snowland-workflow

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }} package
          path: target/release/snowland-${{ matrix.platform }}.zip
